/** Zentrale Konstanten. Quelle: Umsetzungsplan Abschnitt 9. */
export const WS_CONFIG = {
  ARGUMENTS_PER_ROUND: 3,
  ARGUMENT_MIN_CHARS: 8,
  ARGUMENT_MAX_CHARS: 400,
  POINTS_NEED: 1,
  POINTS_DIFFERENTIATOR: 1,
  POINTS_KEY_BONUS: 1,
  POINTS_MATRIX_CORRECT: 1,
  MATRIX_CUPRA_MULTIPLIER: 2,
  STATE_POLL_MS: 2_000,
  PROGRESS_POLL_MS: 3_000,
  PHASE_GRACE_MS: 10_000,
  SCORER_TIMEOUT_MS: 12_000,
  DISPLAY_NAME_MAX: 20,
  LEADERBOARD_TOP_N: 10,
  SESSION_CODE_LENGTH: 6,
} as const;

export const MAX_POINTS_PER_ARGUMENT =
  WS_CONFIG.POINTS_NEED + WS_CONFIG.POINTS_DIFFERENTIATOR + WS_CONFIG.POINTS_KEY_BONUS;
